modLoader="javafml" #mandatory
loaderVersion="[28,)"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="wtbw"
version="${file.jarVersion}"
displayName="What the B Wants"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java" #optional
authors="Naxanria, Sunekaer" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A collection of things and stuffs
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wtbw]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.85,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.wtbw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
